name: Request New Image
description: Request a new image be added to the CANFAR Container Library
title: "[Image Request]: <image-name>"
labels:
  - "request: new image"
  - "area: images"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping grow the CANFAR Container Library.
        This request collects the information needed to review your proposal and link it to a manifest PR.
        You do **not** need to include a manifest YAML draft here; that belongs in the PR.

  - type: input
    id: project_name
    attributes:
      label: Upstream Project Name
      description: The software you want added to the CANFAR Container Library.
      placeholder: e.g. Astropy
    validations:
      required: true

  - type: input
    id: git_repo
    attributes:
      label: Upstream Git Repository URL
      description: Link to the source repository that will be built.
      placeholder: https://github.com/org/repo
    validations:
      required: true

  - type: textarea
    id: maintainers
    attributes:
      label: Upstream maintainer contact info (manifest `maintainers`)
      description: Include name, email, and GitHub/GitLab handle(s).
      placeholder: |
        - Name:
          GitHub / GitLab Username:
    validations:
      required: true

  - type: textarea
    id: relevance
    attributes:
      label: Astronomy Relevance / Use Cases
      description: Why is this image useful to the CANFAR community?
      placeholder: Describe the scientific workflows or tools this enables.
    validations:
      required: true

  - type: checkboxes
    id: osi_license
    attributes:
      label: OSI-approved license confirmation
      description: The source code must be available under an OSI-approved license.
      options:
        - label: I confirm the upstream project uses an OSI-approved license.
          required: true

  - type: input
    id: license_name
    attributes:
      label: License name
      description: Provide the exact license identifier.
      placeholder: MIT, Apache-2.0, GPL-3.0-only
    validations:
      required: true

  - type: input
    id: manifest_pr
    attributes:
      label: Manifest Pull Request
      description: Link to the PR adding the manifest to this repository.
      placeholder: https://github.com/opencadc/canfar-library/pull/123
    validations:
      required: true

  - type: input
    id: image_name
    attributes:
      label: Proposed Image Name (manifest `name`)
      placeholder: astropy
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Target platforms (manifest `build.platforms`)
      description: Select all that should be built.
      multiple: true
      options:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v6
        - linux/arm/v5
        - windows/amd64
    validations:
      required: true

  - type: dropdown
    id: based_on_library
    attributes:
      label: Are you using a CANFAR-provided runtime layer?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: base_rationale
    attributes:
      label: If no, explain why and note any new runtime layer request
      description: Include the reason a new runtime layer is needed (e.g., Julia).
      placeholder: We need a new Julia runtime layer because...


  - type: textarea
    id: maintenance_plan
    attributes:
      label: Maintenance plan / update cadence (recommended)
      description: How will the image be maintained over time?
      placeholder: We'll update tags on each upstream release and respond to CVEs.

  - type: checkboxes
    id: ci_confirmation
    attributes:
      label: Integration tests confirmation
      description: The manifest PR must pass automated checks.
      options:
        - label: I confirm the manifest PR passes automated integration tests.
          required: true
